name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - docker

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          # cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Set build number
        id: set_build_number
        run: echo "::set-output name=BUILD_NUMBER::${GITHUB_RUN_NUMBER}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t jyotiranswain/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }} .
      
      - name: Push Docker image to Docker Hub
        run: |
          docker push jyotiranswain/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - name: Install SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USERNAME }}
        password: ${{ secrets.AWS_EC2_PASSWORD }}
    
    - name: Pull Docker image from Docker Hub
      run: |
        ssh ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }} 'docker pull jyotiranswain/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}'
    
    - name: Stop and remove existing container
      run: |
        ssh ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }} 'docker stop your-container-name || true && docker rm your-container-name || true'
    
    - name: Run Docker container
      run: |
        ssh ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }} 'docker run -d --name your-container-name -p 8080:8080 jyotiranswain/githubaction:${{ steps.set_build_number.outputs.BUILD_NUMBER }}'
